### ISSUE TITLE
React Favicon

### ISSUE THREAD

**Issue by arpitbatra123** [TamalAnwar/periodic-table#2]
The project looks lovely, however, the favicon is still the default react one. The app would look much better if it is changed.

**Comment by TamalAnwar** [comment]
Sure you can make one?

**Comment by arpitbatra123** [comment]
How about this one?
<img src="https://img.icons8.com/color/48/000000/periodic-table-of-elements.png">

**Comment by arpitbatra123** [comment]
Here:
https://drive.google.com/file/d/1bVJxGJwEFb-Z7KfWOFtDWzb3oE8hqeWe/view?usp=sharing

**Comment by TamalAnwar** [comment]
Added the favicon!
